# Site settings
title: Christoph Kittel
email: ckittel@uliege.be
description: >
  Chrisotph Kittel webpage

#baseurl: "/jekyll-doc-theme" # the subpath of your site, e.g. /blog/
url: https://c2kittel.github.io/christophkittel/ # the base hostname & protocol for your site
git_address: https://github.com/c2kittel/christophkittel
#git_edit_address: https://github.com/aksakalli/jekyll-doc-theme/blob/gh-pages

# theme options from https://bootswatch.com/3/
# comment out this to use default Bootstrap
bootwatch: paper # cerulean cosmo custom cyborg darkly flatly journal lumen readable sandstone simplex slate solar spacelab superhero united yeti

# Build settings
markdown: kramdown
highlighter: rouge
# Plugins (previously gems:)
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
  - _posts
  - _docs
timezone: Europe/Berlin
defaults:

navigation:
  - title: "CV"
    url: /cv/
  - title: "Publications"
    url: /publications/
  - title: "Projects"
    url: /publications/
  - title: "Students"
    url: /students/

collections:
#  docs:
#   permalink: /:collection/:path/
#    output: true
#  posts:
#    permalink: /blog/:year/:month/:day/:title/
#    output: true

theme: jekyll-theme-cayman
